<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.polaris</groupId>
        <artifactId>polaris-common</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>polaris-common-context</artifactId>

    <description>
        ruoyi-common-context 用户/租户上下文模块
        提供基于 ThreadLocal 的用户上下文，解耦持久层/日志层对 Sa-Token 的直接依赖
    </description>

    <dependencies>
        <dependency>
            <groupId>com.polaris</groupId>
            <artifactId>polaris-common-core</artifactId>
        </dependency>
    </dependencies>

</project>

